# Generated by Django 3.0.3 on 2020-04-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_number', models.IntegerField()),
                ('cluster_description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['cluster_number'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=200, unique=True)),
                ('full_title', models.TextField(blank=True)),
                ('authors', models.TextField(blank=True)),
                ('publication_year', models.IntegerField(blank=True)),
                ('journal', models.CharField(blank=True, max_length=100)),
                ('link_to_pubmed', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['dataset_name'],
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensembl_id', models.CharField(max_length=50, unique=True)),
                ('gene_symbol', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'genes',
            },
        ),
        migrations.AddIndex(
            model_name='gene',
            index=models.Index(fields=['ensembl_id'], name='magnet_app__ensembl_ec96af_idx'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnet_app.Dataset'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnet_app.Cluster'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnet_app.Gene'),
        ),
    ]
