# Generated by Django 3.0.3 on 2020-04-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
