# Generated by Django 3.0.3 on 2021-01-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet_app', '0004_auto_20210126_0349'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cluster',
            index=models.Index(fields=['cluster_description'], name='magnet_app__cluster_510ef1_idx'),
        ),
    ]
