# Generated by Django 3.0.3 on 2021-02-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magnet_app', '0006_graph_edges'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Graph_edges',
            new_name='Graph_edge',
        ),
    ]
