# Generated by Django 3.0.3 on 2021-03-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet_app', '0009_dataset_dataset_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('gene', 'cluster')},
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['gene', 'cluster'], name='magnet_app__gene_id_af3ed2_idx'),
        ),
    ]
