# Generated by Django 3.0.3 on 2021-03-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet_app', '0010_auto_20210328_2214'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='annotation',
            name='magnet_app__gene_id_af3ed2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('cluster', 'gene')},
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['cluster', 'gene'], name='magnet_app__cluster_1d4f03_idx'),
        ),
    ]
