# Generated by Django 3.0.3 on 2022-01-21 05:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet_app', '0011_auto_20210328_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_list', django.contrib.postgres.fields.jsonb.JSONField()),
                ('background', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
