# Generated by Django 3.0.3 on 2022-01-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet_app', '0012_exampledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampledata',
            name='name',
            field=models.CharField(default='test', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
