# Generated by Django 3.0.3 on 2022-02-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet_app', '0014_dataset_figure_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='figure_info',
            new_name='samples',
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dataset',
            name='figure_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dataset',
            name='genomic_assay',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dataset',
            name='method',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
